# Generated by Django 2.2 on 2019-04-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190429_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_add_author', 'Add author'), ('can_edit_author', 'Edit author'), ('can_delete_author', 'Delete author'))},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('is_librarian', 'Has super powers'),)},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_renew', 'Renew book due date'))},
        ),
    ]
