# Generated by Django 2.2 on 2019-05-10 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190429_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2019, 5, 10)),
            preserve_default=False,
        ),
    ]
